#!/bin/sh
FILE="$HOME/ncl/bookmarks"

if [ "$1" = "f" ] ; then
        cat "$FILE" | dmenu -l 20 | xclip -in -selection clipboard
else
        xclip -out -selection clipboard >> "$FILE"
fi

echo >> "$FILE"
